# Generated by Django 3.1.2 on 2020-12-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='amount',
        ),
    ]
