# Generated by Django 3.1.2 on 2020-12-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutterwave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlwPlanModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('flw_plan_id', models.PositiveIntegerField(blank=True, help_text='Flutterwave plan id. Only required if this is a subscription plan.', null=True, unique=True)),
                ('interval', models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi Annually'), ('yearly', 'Yearly')], help_text='Payment frequency. Only required if this is a subscription plan.', max_length=11, null=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('modal_logo_url', models.URLField(blank=True, help_text='URL to logo image to be displayed on payment modal.', max_length=500, null=True)),
                ('modal_title', models.CharField(blank=True, help_text='Title to be displayed on payment modal.', max_length=200, null=True)),
                ('pay_button_text', models.CharField(default='Sign Up', help_text='Text used for button when displayed in a template.', max_length=100)),
                ('pay_button_css_classes', models.CharField(blank=True, help_text='css classes to be applied to pay button in template.', max_length=200, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
    ]
