# Generated by Django 3.1.2 on 2020-12-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutterwave', '0002_flwplanmodel1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flwplanmodel1',
            options={'verbose_name': 'model', 'verbose_name_plural': 'model'},
        ),
    ]
