# Generated by Django 3.1.2 on 2020-12-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flutterwave', '0003_auto_20201227_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flwplanmodel',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
